name: injecta
description: Library that provides a simple and efficient service registry
repository: https://github.com/kalucky0/injecta
version: 0.2.0

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
